from app.models.schemas import ClauseModel


class LLMService:
    def simplify_clause(self, clause_text: str) -> str:
        return f"Plain-English summary: {clause_text}"

    def generate_counter_clause(self, clause_text: str, goal: str) -> tuple[str, list[str]]:
        suggestion = f"Suggested alternative for '{goal}': {clause_text}"
        notes = ["Preserves core commercial intent.", "Adds clearer balancing language."]
        return suggestion, notes

    def summarize_party(self, party_name: str) -> str:
        return f"{party_name} appears to be an active commercial counterparty with moderate diligence signals."

    def simulate_outcome(self, latest_message: str) -> str:
        return f"Likely outcome based on the current clause set: {latest_message}"

    def build_clause(self, text: str, risk_flag: str) -> ClauseModel:
        return ClauseModel(
            text=text,
            simplifiedText=self.simplify_clause(text),
            riskFlag=risk_flag,  # type: ignore[arg-type]
            explanation="Stub explanation generated by the AI service.",
            counterClauseSuggestion="Stub counter-clause suggestion.",
        )


llm_service = LLMService()

